//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrialEnterpriseWPF.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
